# Generated by Django 4.0.4 on 2022-05-20 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='username@company.com', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.product')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.role')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.state')),
                ('ticketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.user'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.product'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.severity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.state'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.companytype'),
        ),
    ]
