# Generated by Django 4.0.4 on 2022-05-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='ticketNumber',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='handler',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.user'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.product'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='severity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.severity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(default='username@company.com', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.state'),
        ),
    ]
