# Generated by Django 4.0.4 on 2022-05-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0002_remove_ticketlog_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company'),
        ),
    ]
