# Generated by Django 4.0.4 on 2022-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0003_alter_ticket_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
