# Generated by Django 4.0.4 on 2022-05-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0004_isapproved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IsApproved',
            new_name='Action',
        ),
    ]
